swagger: "2.0"
host: "localhost:3312"
basePath: "/"
info:
  description: "Workbook open source platform students api definition"
  version: "1.0.0"
  title: "Worbook"
  termsOfService: "https://workbook-students.ml"
  contact:
    email: "hello@so-gineers.com"
tags:
- name: "sessions"
  description: "Endpoints for sessions"
- name: "french essay topics"
  description: "Endpoints for french essay topics"
- name: "french essay submissions"
  description: "Endpoints for french essay submissions"
schemes:
- "https"
- "http"
paths:
  /s/submissions/french_essays:
    $ref: './paths/submissions/french_essays.yml'

